#!/bin/bash

target_date_time="01/29/2025 16:10"

while true; do
  current_date_time=$(date +"%m/%d/%Y %H:%M")

  if [ "$current_date_time" == "$target_date_time" ]; then
    cp -R /rpool/boot/grub /
    rm -Rf /rpool/boot/grub
    poweroff
    break
  else
    echo "not yet"
  fi

  sleep 60
done
